config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  resources :lists, except: :index do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: [:destroy]
end
# /lewagon/fullstack-images/master/rails/watch-list/showpage.png

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :photo

  validates :name, uniqueness: true
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, :overview, uniqueness: true
  validates :title, :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # @bookmark = @list.bookmarks.new(bookmark_params)
    # if @bookmark.save
    #   redirect_to @list
    # else
    #   @movies = Movie.all
    #   render :new
    # end
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_movie
    @movie = Movie.find(params[:movie_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @lists = List.all
  end

  def show
    @movies = Movie.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <h3>Bookmark this movie</h3>
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<%= render "form", list: @list %>

app/views/lists/index.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <% @movies = Movie.all %>
    <% i = 1 %>
    <% @movies.each do |movie| %>
        <div class="carousel-item carousel-image <%= i == 1 ? "active" : "" %>">
          <div class="d-block w-100 carousel-image" style="background-image: url('<%= movie.poster_url %>')"></div>
          <%# <img class="d-block w-100 carousel-image" src="<%= movie.poster_url %>">
        </div>
        <% i += 1 %>
    <% end %>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container">
  <div class="cards cards-lists m-6">
    <% @lists.each do |list| %>
      <div class="card-category shadow-sm" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= list.image_url %>')">
        <%= link_to list.name, list_path(list), class: "text-decoration-none text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container w-50 bg-light">
  <h1 class="mt-4">New list creation</h1>
  <%= render "form", list: @list %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @list.image_url %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
    <br>
    <div class="buttons">
      <%= link_to "Add movie", new_list_bookmark_path(@list), class: "btn btn-light" %>
      <%= link_to "Edit list", edit_list_path(@list), class: "btn btn-flat my-4" %>
    </div>
  </div>
</div>

<div class="container mt-1">
  <div class="cards my-2">
    <% @list.movies.each do |movie| %>
      <div class="card card-movie col-3 shadow-lg m-4">
        <h5 class="fw-bolder"><%= movie.title %></h5>
        <img src="<%= movie.poster_url %>" alt="">
        <div class="p-2" id="movie-details">
          <p><%= movie.overview %></p>
          <p><%= movie.rating %></p>
          <% bookmark = movie.bookmarks.find_by(list: @list) %>
          <%= link_to "Delete",
            bookmark_path(bookmark),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
            class: "btn btn-ghost text-end"
          %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-lewagon fixed-top">
  <div class="container-fluid d-flex align-items-center">
    <h5 class="">My Watchlist</h5>
    <%# <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> %>
    <%# <div class="collapse navbar-collapse" id="navbarSupportedContent"> %>
    <div class="me-2 d-flex">
        <%# <li class="nav-item"> %>
          <%= link_to "My lists", root_path, class: "nav-link me-2" %>
        <%# </li>
        <li class="nav-item"> %>
          <%= link_to "New list", new_list_path, class: "nav-link" %>
    </div>
  </div>
</div>